### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-switcher-platform

### ISSUE THREAD

**Issue by fire1ce** [nitaybz/homebridge-switcher-platform#30]
Running as Docker Container (ubuntu) on raspberry bi.

[6/18/2022, 8:08:09 PM] ====================
[6/18/2022, 8:08:09 PM] ERROR LOADING PLUGIN homebridge-switcher-platform:
[6/18/2022, 8:08:09 PM] ReferenceError: SEPARATED_SWING_REMOTES is not defined
    at Object.<anonymous> (/homebridge/node_modules/.pnpm/switcher-js2@1.3.8/node_modules/switcher-js2/src/switcher.js:43:25)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/homebridge/node_modules/.pnpm/switcher-js2@1.3.8/node_modules/switcher-js2/index.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
[6/18/2022, 8:08:09 PM] ====================

**Comment by nitaybz** [comment]
FIXED... sorry

**Comment by fire1ce** [comment]
> FIXED... sorry

No need to be sorry.
Curiosity: why you don't have  CI Actions for deploy?

**Comment by nitaybz** [comment]
To be honest... I'm not a developer as a profession, and I'm doing this on my own free time so some implementations are quick and dirty (unfortunately).

But I've added eslint to the code so those specific errors should not happen again

**Comment by fire1ce** [comment]
I'm not a "developer as a profession" too, but it will make you life much easer if you learn how to use them. 
Any way thanks for the attention. Very Appreciated. 

New version work as intended.
