### ISSUE TITLE
Occasionally I have to restart my switcher plugin - error seen in the log

### ISSUE THREAD

**Issue by idanhod-cyco** [nitaybz/homebridge-switcher-platform#55]
A bit about my setup:
I have about a dozen switcher switches. One for boiler and 6 windows blinds and 15 light switches.
They are all connected to my HB with switcher plugin that worked very well for me. 

Sometimes, after a long break (night), the automations break. a sensor triggers the light, and the lights are not turning on. Reseting the HB is the solusion. I noticed seeing some logs about errors - it correlates with the failed switch triggered.

Log:
[1/15/2024, 10:03:45 AM] [Switcher Platform] Switcher Light_14C9 - Setting Light1 Power to ON
[1/15/2024, 10:03:46 AM] [Switcher Platform] ERROR for Switcher Light_14C9
[1/15/2024, 10:03:46 AM] [Switcher Platform] Error: login failed due to an error: read ECONNRESET
    at Switcher._login3 (/usr/local/lib/node_modules/homebridge-switcher-platform/node_modules/switcher-js2/src/switcher.js:802:27)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Switcher._run_general_command (/usr/local/lib/node_modules/homebridge-switcher-platform/node_modules/switcher-js2/src/switcher.js:835:16)
[1/15/2024, 10:06:06 AM] [Switcher Platform] Switcher Light_16D1 - Setting Light2 Power to OFF
[1/15/2024, 10:06:06 AM] [Switcher Platform] Switcher Light_16D1 - Setting Light1 Power to OFF
[1/15/2024, 10:06:06 AM] [Switcher Platform] ERROR for Switcher Light_16D1
[1/15/2024, 10:06:06 AM] [Switcher Platform] Error: login failed due to an error: read ECONNRESET
    at Switcher._login3 (/usr/local/lib/node_modules/homebridge-switcher-platform/node_modules/switcher-js2/src/switcher.js:802:27)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Switcher._run_general_command (/usr/local/lib/node_modules/homebridge-switcher-platform/node_modules/switcher-js2/src/switcher.js:835:16)

**Comment by itaywol** [comment]
Having this issue also 😕

**Comment by Tapuziyahoo** [comment]
+1:

[1/26/2026, 9:31:35 AM] [Switcher Platform] ERROR for Switcher Light_0AD1
[1/26/2026, 9:31:35 AM] [Switcher Platform] Error: login failed due to an error: read ECONNRESET
    at Switcher._login3 (/var/lib/homebridge/node_modules/homebridge-switcher-platform/node_modules/switcher-js2/src/switcher.js:802:27)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Switcher._run_general_command (/var/lib/homebridge/node_modules/homebridge-switcher-platform/node_modules/switcher-js2/src/switcher.js:835:16)

**Comment by Tapuziyahoo** [comment]
@nitaybz could you please look into this?
Would gladly provide any additional logging if necessary..

**Comment by nitaybz** [comment]
Took another look at this and the diagnosis is clear, fixed in v4.6.0 (just published, requires switcher-js2 1.7.0 which is now the dependency).

What was happening: the library kept one cached TCP socket per device. After a long idle (overnight, your WiFi reassociating, the device firmware doing whatever) that socket would be dead on the device's end, but Node had not noticed yet because the default OS-level TCP keepalive is around 2 hours. The next command would write to the dead socket and get ECONNRESET on the login response. The library logged the error but did not self-heal, so every subsequent command kept hitting the same dead state until you restarted Homebridge.

Three fixes in 1.7.0:
- when the cached socket emits error or close, the library now immediately drops it (and the cached login session) so the next command opens a fresh connection.
- TCP keepalive is now 30 seconds instead of the OS default, so dead idle connections are detected within ~30s.
- power and general commands now retry once automatically on connection failure, so the very first command after idle should just work without you noticing anything.

Update to 4.6.0 and you should not need to restart Homebridge for this anymore. Please ping me here if it still happens after 24 hours of uptime, with logs.

Sorry for the long delay on this. I'm not actively using Homebridge anymore, but this one has been bugging me too.

**Comment by Tapuziyahoo** [comment]
Thanks a lot @nitaybz !
